matrix:
  allow_failures:
    - compiler: gcc
    - language: android
  include:
    # linux
    - compiler: gcc
      language: cpp
      env: testenv="linux gcc" myos=linux
    - compiler: gcc
      language: cpp
      env: testenv="mingw-w64 windows cross compile, libyabause only" myos=winx64
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
    - compiler: clang
      language: android
      env: testenv="android port" myos=android
      jdk: oraclejdk8
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      android:
        components:
          - tools
          - platform-tools
          - build-tools-24.0.3
          - android-24
    # osx
    - env:
        - testenv="os x cross ios" myos=ios myarch=armv
      os: osx
      xcode_sdk: iphonesimulator11.4
      compiler: clang
    - env:
        - testenv="os x cross ios 7+" myos=ios7 myos=ios myarch=arm64
      os: osx
      xcode_sdk: iphonesimulator11.4
      compiler: clang
    - env: testenv="os x cocoa port" myos=mac
      os: osx
      compiler: clang
    - os: osx
      env: testenv="os x qt port" myos=macqt
      compiler: clang
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Hkf9HZos0iEaGcVtNq5IVFVBd0/t5jwHppnV5SkQrJ+vRXyUSEmwlg0u48DgFqaFlpWQhpCLlkQhS/ay7cbH6BZLk8TkLGC8EVJ7KdPI9w4q5XAzU0+hYuZ5FyxzlQO/kJTe8RewQaBa7+NXgdJMU4f+eJMbcoBiDPHuiQ+29qUkS6B/B8x+9oKNzXozxR0aoXGtvCMRcbPEnBtTTVzyldC0IqDhZB2+a7MnZOKOg43uuRMvFUPh1efyZtCDm6o3EmzQ+lMwkGBQ2qq7KQFJ18DhOhg9EYD8MKd+qhtTDoECJ2yZ34BiK4no+Crlu8Jv2XwThEg17W4pZwRjq6pDCDhWrBY80Z0c24s36MN4cLoKMsHEEmqtj0XrargA4qIyDRq+Q+92DrU0eIMl/YWJN+ogIKajI9bCGF3JSpLT799+cioDEEzJk2CBKCJCWLGV34OXY7crzjE+YpA69Oz/3kUyHFPXAiSazV20QaV2yd4ul580Ak6xxdZQSyWRGbVzvx3YchASlP4ulH6icoDqQMJldw78kexca6TZ88rNDjfdFEnLHyttsxoQN6Cwf69/P4LyIAG93PhD3dV124omhS6yBPGtZF8+f0+k/vJJN1iJ6xPEiovJlEOwfap1bNBusOo7i0y5Dm3RR+RkDFIsGZwOkB3ZbjTpE7mCoe0eMkg="
addons:
  coverity_scan:
    project:
      name: b23prodtm/yabause
      description: Build submitted via Travis CI
    notification_email: b23prodtm@gmail.com
    build_command_prepend: ../../.travis/${myos}-configure
    build_command: make
    branch_pattern: coverity_scan
language: objective-c
sudo: false
before_install:
# Coverity Scan certificate (global secure: COVERITY_SCAN_TOKEN)
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen zlib; fi
# Cmake build directory
  - cd yabause
  - mkdir build
  - cd build
script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ../../.travis/${myos}-configure && make; fi
after_success:
  - cpack -G ZIP -D CPACK_PACKAGE_FILE_NAME=yabause-v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}-${myos}
  - git config --local user.name ${GIT_USER}
  - git config --local user.email ${GIT_MAIL}
  - git tag --force "v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}"
deploy:
  provider: releases
  api_key:
    secure: oYQp54i5P9hs27pWaBuhgvVQGnLi7bVxoErINkP1Iu0PPv6jfq9YVS+MvbWi8+VWBrV7F1l+6xe9jeA41P+9y9+KnIgoO9+57H28Apgr9+yrbt/JqtM2o56Yrrpl9PJPaG82aBT5kRMxvPBHpWP0p3aCOcTt9oNM3AEipbyiS1bcA02l7CEqPtVh19gO79jqxXTainkdmFChRVYhlnbIIuSleGuBrtbnnUfwiZ94anqj4hOz+A9EyWIa/FtC2J3s4dV6USXoiiuGuw2ekvXI6YfQyTOdtmWLqmp+LAHdOvnSKMP10JBKy1Vi4EJ8RHt0X160wBLPXsN0mngx1OmPAWwfrBgZ5eu187w1GKQHMHk4/l4exVqNhW3t8mSNMwdCBu80mF3HL/qWfkdKiA1Ryeq/t18usMLNCKRcKgeQ3OsigZSTvDZMg7xLSNOkcZ/XpURR0RABvhUMkRLdsrsnKs8DdLo++dTHWPr01hWXucq+cp3LYtuRLMmJrzzTZbNC7vUC1gnEtypZQ98B92B5hn9hO/+BpY+k1csYPtgPJMofOqliWs79YNe6HsctH4WnEJKXaPWRPse16PzPTT4ENjHZRV407erqvjx56i79BbE44caXHZA0kwQkhxD9WTfvvS+3Bm71BuNs73pV2D+NHNGEy5uJmMeQCrBXo4dghFc=
  file_glob: true
  file: 'yabause-v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}*'
  skip_cleanup: true
  on:
    repo: b23prodtm/yabause
    branch: feature/*
