matrix:
  allow_failures:
    - compiler: clang
  include:
    # linux
    - compiler: gcc
      language: cpp
      env: testenv="linux gcc" myos=linux
    - compiler: gcc
      language: cpp
      env: testenv="mingw-w64 windows cross compile, libyabause only" myos=winx64
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
    - compiler: clang
      language: android
      env: testenv="android port" myos=android
      jdk: oraclejdk8
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      android:
        components:
          - tools
          - platform-tools
          - build-tools-24.0.3
          - android-24
    # osx
    - env:
        - testenv="os x cross ios" myos=ios myarch=armv
      os: osx
      xcode_sdk: iphonesimulator11.4
      compiler: clang
    - env:
        - testenv="os x cross ios 7+" myos=ios7 myos=ios myarch=arm64
      os: osx
      xcode_sdk: iphonesimulator11.4
      compiler: clang
    - env: testenv="os x cocoa port" myos=mac
      os: osx
      compiler: clang
    - os: osx
      env: testenv="os x qt port" myos=macqt
      compiler: clang
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "4eLN73nrbAg+MO/gabXdwTshOy4xgDLHSLjmupgCnFjk5SMQqBFkCwqVCDNPmwQQ4BMaxjTjWmKkVOUaaP4Yzkw2rSBzmddoA2OefKhXVYgT0WTTYUcDDFmv/m7daXXnCUHGdeGbv6l3Tzh71JwhUs+tZ6tcIv0u1htJ3l7hSrqJ4Gx/siRWYAt7ytUThJyhW/hC+HQ7Ayrdcgk2+ugsLLA9P0p9E0RqI5BIWWX6jAAl1igeec5uumYlUUdx1YErLaVrkrCQm0YHa6wkqJs7rhU3i1Asdseh9SI1avOsx7Et25kdHVWoA873wwoVKQRgd0PpO8Al9RP4/sqs+1GHnz7CDwboi+MurnDkiWncsYXXYQYYO1WUcPvg5YEf3a2/THE27WWF65wfYXDUrQG5bSu1nk/nX/kBee7l7ogfYdiicrHF1ZIZ/eyavoh2XOTZl+0uKwajuwcoVYJYPT7DXTf3RK31FFmVox76/RcN2hRgvgdSqhG+feCp3aV4niqGWtA4GkzLH0tbulPKywbSdN1CQsn2vtOOW8CU/VndDT9vR9bnFl0ir4rvysYGKgGmsnEiNpS2zCLTDhkQe4c8YUv/s6OXYB5okRKYMqr31tpjINBSpXqwYbTRiGBK6T1oFRNCHVlMi5DgZiPjRr3M0IQD+dSuonZXgLe51K858RI="
addons:
  coverity_scan:
    project:
      name: b23prodtm/yabause
      description: Build submitted via Travis CI
    notification_email: b23prodtm@gmail.com
    build_command_prepend: .travis/${myos}-configure
    build_command: make
    branch_pattern: coverity_scan
language: objective-c
sudo: false
before_install:
# Coverity Scan certificate (global secure: COVERITY_SCAN_TOKEN)
- if ([[ "${TRAVIS_JOB_NUMBER##*.}" != "1" ]] && [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]); then echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi
# Homebrew packages
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen zlib; fi
# Cmake build directory
- cd yabause
- mkdir build
- cd build
script:
  - cd ../build
  - ../../.travis/${myos}-configure
  #- echo | g++ -dM -E - #echo predefined variables
  - make
after_success:
  - cpack -G ZIP -D CPACK_PACKAGE_FILE_NAME=yabause-v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}-${myos}
  - git config --local user.name ${GIT_USER}
  - git config --local user.email ${GIT_MAIL}
  - git tag "v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}"
deploy:
  provider: releases
  api_key:
    secure: oYQp54i5P9hs27pWaBuhgvVQGnLi7bVxoErINkP1Iu0PPv6jfq9YVS+MvbWi8+VWBrV7F1l+6xe9jeA41P+9y9+KnIgoO9+57H28Apgr9+yrbt/JqtM2o56Yrrpl9PJPaG82aBT5kRMxvPBHpWP0p3aCOcTt9oNM3AEipbyiS1bcA02l7CEqPtVh19gO79jqxXTainkdmFChRVYhlnbIIuSleGuBrtbnnUfwiZ94anqj4hOz+A9EyWIa/FtC2J3s4dV6USXoiiuGuw2ekvXI6YfQyTOdtmWLqmp+LAHdOvnSKMP10JBKy1Vi4EJ8RHt0X160wBLPXsN0mngx1OmPAWwfrBgZ5eu187w1GKQHMHk4/l4exVqNhW3t8mSNMwdCBu80mF3HL/qWfkdKiA1Ryeq/t18usMLNCKRcKgeQ3OsigZSTvDZMg7xLSNOkcZ/XpURR0RABvhUMkRLdsrsnKs8DdLo++dTHWPr01hWXucq+cp3LYtuRLMmJrzzTZbNC7vUC1gnEtypZQ98B92B5hn9hO/+BpY+k1csYPtgPJMofOqliWs79YNe6HsctH4WnEJKXaPWRPse16PzPTT4ENjHZRV407erqvjx56i79BbE44caXHZA0kwQkhxD9WTfvvS+3Bm71BuNs73pV2D+NHNGEy5uJmMeQCrBXo4dghFc=
  file_glob: true
  file: 'yabause-v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}*'
  skip_cleanup: true
  on:
    repo: b23prodtm/yabause
    branch: feature/*
